name: Docker lint

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
